<a href="https://colab.research.google.com/github/RahulReady/DPA-Final-Project/blob/master/LDA_features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install gensim==3.4.0

     |████████████████████████████████| 22.6MB 1.6MB/s 
  Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0:
      Successfully uninstalled gensim-3.6.0


In [151]:
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer 
sid_obj = SentimentIntensityAnalyzer() 

In [94]:
!pip install imblearn
from imblearn.under_sampling import RandomUnderSampler

In [3]:
!sudo apt-get install python3-dev default-libmysqlclient-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dev is already the newest version (3.6.7-1~18.04).
The following NEW packages will be installed:
  default-libmysqlclient-dev libmysqlclient-dev
0 upgraded, 2 newly installed, 0 to remove and 25 not upgraded.
Need to get 996 kB of archives.
After this operation, 6,022 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libmysqlclient-dev amd64 5.7.29-0ubuntu0.18.04.1 [992 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 default-libmysqlclient-dev amd64 1.0.4 [3,736 B]
Fetched 996 kB in 1s (835 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This fr

In [4]:
pip install PyDrive

In [5]:

!pip install --upgrade setuptools
!pip install wheel
!pip install pattern
!pip install mysqlclient

Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/dist-packages (46.1.3)
     |████████████████████████████████| 22.3MB 1.3MB/s 
     |████████████████████████████████| 92kB 11.5MB/s 
     |████████████████████████████████| 194kB 60.7MB/s 
     |████████████████████████████████| 5.6MB 32.0MB/s 
     |████████████████████████████████| 5.5MB 56.5MB/s 
     |████████████████████████████████| 419kB 58.7MB/s 
     |████████████████████████████████| 13.7MB 8.9MB/s 
     |████████████████████████████████| 92kB 12.3MB/s 
  Created wheel for pattern: filename=Pattern-3.6-cp36-none-any.whl size=22332723 sha256=4dcdc2217e97ba76afd363d9aa169b405a166a91a5715bda42212892dfdce31d
  Stored in directory: /root/.cache/pip/wheels/dc/9a/0e/5fb1a603ed4e3aa8722a88e9cf4a82da7d1b63e3d2cc34bee5
  Created wheel for mysqlclient: filename=mysqlclient-1.4.6-cp36-cp36m-linux_x86_64.whl size=98418 sha256=917ee2c087c04f58e8cbf0f05fed023c8e1376451cfcfae908cdefecb195fd0f
  Stored in directory: /root

In [6]:
!pip install pandarallel
from pandarallel import pandarallel
pandarallel.initialize()

INFO: Pandarallel will run on 40 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.


In [7]:
import numpy as np
import re
import pandas as pd
import gensim
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk import word_tokenize
stop_words = set(stopwords.words('english'))
from gensim.models import LdaModel, LdaMulticore
import gensim.downloader as api
from gensim.utils import  lemmatize
from gensim import corpora
from nltk.corpus import stopwords
import re
import logging
nltk.download('punkt')
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s')
logging.root.setLevel(level=logging.INFO)
stop_words = stopwords.words('english')
stop_words.extend(['restaurant','food','place','las','vegas','hotel'])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [0]:
from gensim.models.phrases import Phrases, Phraser
import multiprocessing
import tqdm
from sklearn import utils
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score,confusion_matrix,precision_recall_fscore_support,classification_report
import ast
from sklearn.preprocessing import  StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_recall_fscore_support

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
from google.colab import drive

In [10]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
review_Dataset = pd.read_csv('/content/drive/Shared drives/DPA Final Project/review_dataset_features.csv')

In [0]:
review_Dataset =review_Dataset.drop(columns= 'Unnamed: 0')

In [0]:
Dataset = pd.read_csv('/content/drive/Shared drives/DPA Final Project/y_file.csv')

In [0]:
y_file = pd.read_csv('/content/drive/Shared drives/DPA Final Project/y_file.csv')

In [0]:
def inspection_grade(x):
  if x <= 10:
    return 'A'
  elif x<=20:
    return 'B'
  else :
    return 'C'    

In [0]:
Dataset['inspection_grade'] = Dataset.average_demerits.apply(lambda x : inspection_grade(x))

In [0]:
Dataset =Dataset.drop(columns= 'Unnamed: 0')

In [0]:
 Dataset['Date'] =  pd.to_datetime(Dataset.inspection_date)

In [0]:
Dataset['previous_grade']=Dataset.groupby('business_id')['inspection_grade'].apply(lambda x : x.shift(1))

In [0]:
Dataset.loc[Dataset.previous_grade.isna(),'previous_grade'] = 'NA'

In [18]:
Dataset.previous_grade.value_counts()

A     86923
B     16344
NA     5540
C      4583
Name: previous_grade, dtype: int64

In [0]:
Dataset= Dataset[Dataset.Date.dt.year >2012].reset_index(drop=True)

In [0]:
def get_rows(df,time_period,b_id,date_input):
    temp_df = df[df.business_id == b_id]
    date_min = date_input - \
       pd.offsets.DateOffset(months=time_period)
    temp_df = temp_df[(temp_df['date'] < date_input) & (temp_df['date']>=date_min)].reset_index(drop = True)
    return temp_df[[str(i) for i in range(100)]].mean()
   

In [0]:
def get_ratings(df,time_period,b_id,date_input):
    temp_df = df[df.business_id == b_id]
    date_min = date_input - \
       pd.offsets.DateOffset(months=time_period)
    temp_df = temp_df[(temp_df['date'] < date_input) & (temp_df['date']>=date_min)].reset_index(drop = True)
    return temp_df['stars'].mean()

In [0]:
def get_sentimnet_Score(df,time_period,b_id,date_input):
    temp_df = df[df.business_id == b_id]
    date_min = date_input - \
       pd.offsets.DateOffset(months=time_period)
    temp_df = temp_df[(temp_df['date'] < date_input) & (temp_df['date']>=date_min)].reset_index(drop = True)
    temp_df['polarity_scores'] = temp_df.text.apply(lambda x:sid_obj.polarity_scores(x).get('compound'))
    return temp_df['polarity_scores'].mean()

In [185]:
get_sentimnet_Score(review_Dataset,12,Dataset.business_id[0],Dataset.Date[0])

0.72482

In [0]:
review_Dataset.date = pd.to_datetime(review_Dataset.date)

In [0]:
review_Dataset = review_Dataset[~review_Dataset.text.isna()]

In [0]:
def get_features(b_id,date,y_file):
    temp_df= y_file[y_file.business_id == b_id]
    temp_df = temp_df[temp_df.inspection_date < date]
    if(temp_df.empty):
      return [None,0]
    else:
      return [temp_df.average_demerits.mean(),temp_df.average_demerits.count()]

In [0]:
Dataset[list(range(100))] = Dataset.parallel_apply(lambda x : get_rows(review_Dataset,12,x['business_id'],x['Date']),axis=1,result_type ='expand')

In [0]:
Dataset['ratings'] = Dataset.parallel_apply(lambda x : get_ratings(review_Dataset,12,x['business_id'],x['Date']),axis=1)

In [188]:
Dataset['sentiment_score'] = Dataset.parallel_apply(lambda x : get_sentimnet_Score(review_Dataset,12,x['business_id'],x['Date']),axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
Dataset= Dataset[~Dataset.ratings.isna()]

In [194]:
Dataset[['previous_demerits_avg','no_of_inspections']]=Dataset.parallel_apply(lambda x : get_features(x['business_id'],x['inspection_date'],y_file),axis =1,result_type ='expand')

Process ForkPoolWorker-296:
Process ForkPoolWorker-323:
Process ForkPoolWorker-307:
Process ForkPoolWorker-303:
Process ForkPoolWorker-299:
Process ForkPoolWorker-300:
Process ForkPoolWorker-297:
Process ForkPoolWorker-326:
Process ForkPoolWorker-291:
Process ForkPoolWorker-313:
Process ForkPoolWorker-325:


KeyboardInterrupt: ignored

Process ForkPoolWorker-328:
Process ForkPoolWorker-308:
Process ForkPoolWorker-292:
Process ForkPoolWorker-304:
Traceback (most recent call last):
Traceback (most recent call last):
Process ForkPoolWorker-305:
Process ForkPoolWorker-314:
Process ForkPoolWorker-320:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process ForkPoolWorker-311:
Process ForkPoolWorker-324:
Process ForkPoolWorker-315:
Process ForkPoolWorker-310:
Process ForkPoolWorker-322:
Traceback (most recent call last):
Traceback (most recent call last):
Process ForkPoolWorker-309:
Traceback (most recent call last):
Process ForkPoolWorker-319:
Process ForkPoolWorker-301:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
Process ForkPoolWorker-302:
Process ForkPoolWorker-294:
  File "/usr/lib/python3.6/multiprocessing/p

In [0]:
def pass_fail(x):
  if (x=='A'):
    return (1)
  else:
    return  (0)

In [0]:
Dataset['pass'] = Dataset.inspection_grade.apply(lambda x:pass_fail(x))

In [0]:
Dataset.loc[Dataset['previous_demerits_avg'].isna(),'previous_demerits_avg'] = Dataset.previous_demerits_avg.median()

In [0]:
Dataset[['previous_A','previous_B','previous_C']] = pd.get_dummies(Dataset.previous_grade).drop(columns = 'NA')

In [98]:
Dataset.isna().sum()

business_id            0
inspection_date        0
inspection_count       0
average_demerits       0
inspection_grade       0
                    ... 
pass                   0
previous_A             0
previous_B             0
previous_C             0
ratings             9599
Length: 114, dtype: int64

In [246]:
Dataset['pass'].value_counts()

1    40990
0    11384
Name: pass, dtype: int64

In [0]:
train,test = train_test_split(Dataset,test_size = 0.2,stratify = Dataset['pass'],random_state =100)

In [249]:
test['pass'].value_counts()

1    8198
0    2277
Name: pass, dtype: int64

In [0]:
X_train = train[ ['sentiment_score'] +  ['ratings'] + ['previous_A','previous_B','previous_C']+['previous_demerits_avg','no_of_inspections']]
X_test = test[  ['sentiment_score'] + ['ratings'] + ['previous_A','previous_B','previous_C']+['previous_demerits_avg','no_of_inspections']] 

In [0]:
Y_train = train['pass']

In [0]:
Y_test = test['pass']

In [0]:
sc = StandardScaler()

In [0]:
rus = RandomUnderSampler(random_state=42)

In [333]:
X_train_under,Y_train_under= rus.fit_resample(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [0]:
X_train_fit = sc.fit_transform(X_train_under)

In [0]:
X_test_fit  = sc.fit_transform(X_test)

In [337]:
clf = RandomForestClassifier(n_estimators=100,min_samples_split=4,min_samples_leaf=2)
clf.fit(X_train_fit,Y_train_under)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [341]:
logreg = LogisticRegression(n_jobs=1, C=1e5)
logreg.fit(X_train_fit,Y_train_under)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=1, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [293]:
clf = GaussianNB()
clf.fit(X_train_fit,Y_train_under)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = logreg.predict(X_test_fit )

In [343]:
accuracy_score(y_true=Y_test,y_pred=y_pred)

0.6339856801909308

In [344]:
print(classification_report(y_true=Y_test,y_pred=y_pred, target_names=['fail','pass']))

              precision    recall  f1-score   support

        fail       0.33      0.66      0.44      2277
        pass       0.87      0.63      0.73      8198

    accuracy                           0.63     10475
   macro avg       0.60      0.64      0.58     10475
weighted avg       0.75      0.63      0.67     10475



In [314]:
confusion_matrix(Y_test,y_pred,labels=[1,0])

array([[5217, 2981],
       [ 930, 1347]])

In [0]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [320]:
precision_score(Y_test,y_pred)

0.8487066861883846

In [322]:
recall_score(Y_test,y_pred)

0.6363747255428153

In [316]:
precision_recall_fscore_support(Y_test,y_pred)

(array([0.31122921, 0.84870669]),
 array([0.59156785, 0.63637473]),
 array([0.40787282, 0.72736145]),
 array([2277, 8198]))